/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginDialog.java
 *
 * Created on Dec 18, 2011, 8:41:12 PM
 */
package com.weakhis.aplikasiabsensi.ui.view;

import com.weakhis.aplikasiabsensi.presenter.LoginController;
import java.beans.PropertyChangeEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author kojek
 */
public class LoginDialog extends JDialog implements IView {
    
    private LoginController loginController;
    
    private boolean enabledLogin;

    /** Creates new form LoginDialog */
    public LoginDialog(javax.swing.JFrame parent, boolean modal, LoginController loginController) {
        super(parent, modal);
        this.loginController = loginController;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLoginUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLoginPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(298, 117));

        txtLoginUser.setName(""); // NOI18N

        jLabel1.setText("Nama Pengguna");
        jLabel1.setName("jLabel1"); // NOI18N

        txtLoginPass.setName(""); // NOI18N

        jLabel2.setText("Kata Sandi");
        jLabel2.setName("jLabel2"); // NOI18N

        exitButton.setText("Keluar"); // NOI18N
        exitButton.setName("exitButton"); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.setName("loginButton"); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton))
                    .addComponent(txtLoginUser, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(txtLoginPass))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(loginButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(validateForm()){
            loginController.validateLogin(txtLoginUser.getText(), (new String(txtLoginPass.getPassword())));
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
  
        
    public boolean validateForm(){
        if(txtLoginUser.getText().length()==0){
            JOptionPane.showMessageDialog(MainFrame.getInstance(), "Nama Pengguna tidak boleh kosong!");
            return false;
        } else if(txtLoginPass.getPassword() == null || txtLoginPass.getPassword().length==0){
            JOptionPane.showMessageDialog(MainFrame.getInstance(), "Kata Sandi tidak boleh kosong!");
            return false;
        }
        return true;
    }

    public boolean isEnabledLogin() {
        return enabledLogin;
    }

    public void setEnabledLogin(boolean enabledLogin) {
        this.enabledLogin = enabledLogin;
        if(enabledLogin){
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(MainFrame.getInstance(), "Nama Pengguna dan Kata Sandi tidak cocok!");
        }
    }
    
    @Override
    public void modelPropertyChange(PropertyChangeEvent evt) {
        if(loginController.ENABLED_LOGIN_PROPERTY.equals(evt.getPropertyName())){
            setEnabledLogin((Boolean) evt.getNewValue());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField txtLoginPass;
    private javax.swing.JTextField txtLoginUser;
    // End of variables declaration//GEN-END:variables

    
}
